HOSTS:
  ubuntu-1604:
    roles:
      - default
    platform: ubuntu-16.04-amd64
    hypervisor: vmpooler
    template: Delivery/Quality Assurance/Templates/vCloud/ubuntu-1604-x86_64
CONFIG:
  nfs_server: none
  consoleport: 443
  datastore: instance0
  folder: Delivery/Quality Assurance/Enterprise/Dynamic
  resourcepool: delivery/Quality Assurance/Enterprise/Dynamic
  pooling_api: http://vcloud.delivery.puppetlabs.net/
  type: foss

# HOSTS:
#   kube-master:
#     roles:
#       - default
#     platform: ubuntu-16.04-amd64
#     box: puppetlabs/ubuntu-16.04-64-nocm
#     box_url: https://vagrantcloud.com/puppetlabs/ubuntu-16.04-64-nocm
#     hypervisor: vagrant
#     ip: 172.17.10.101
# CONFIG:
#   log_level: verbose
#   type: foss
